name: CI

on: push

jobs:

  Linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule update --init --recursive

      - name: Build CALM
        working-directory: ./calm
        run: |
          git apply --verbose --ignore-space-change --ignore-whitespace ../sdl2-ttf.patch
          docker run --env CI=true -v $PWD:/calm -w /calm fedora:32 bash build/build.sh
          ls -lah .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CALM Linux
          if-no-files-found: error
          path: |
            calm/*.tgz

  macOS:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]

    env:
      CI_MATRIX_OS: ${{ matrix.os }}
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule update --init --recursive

      - name: Setup AppleScript for macOS 13
        if: ${{ matrix.os == 'macos-13' }}
        run: |
          sudo sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.finder',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e66696e64657200000003',NULL,1592919552);"
          sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.finder',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e66696e64657200000003',NULL,1592919552);"

      - name: Build CALM
        working-directory: ./calm
        run: |
          git apply --verbose --ignore-space-change --ignore-whitespace ../sdl2-ttf.patch
          bash build/build.sh
          ls -lah .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CALM macOS
          if-no-files-found: error
          path: |
            calm/*.dmg

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule update --init --recursive


      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build CALM
        shell: cmd
        working-directory: ./calm
        run: |
          git apply ..\\sdl2-ttf.patch
          build\\build.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CALM Windows
          if-no-files-found: error
          path: |
            calm/*.zip

# Lem

  Lem-Linux:
    needs: Linux
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule update --init --recursive


      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: CALM Linux

      - name: Build Lem
        run: |
          set -x
          rm -rf calm
          ls -lah
          tar xvf calm.tgz
          ls -lah calm
          cp -R lem calm/quicklisp/local-projects/lem
          cp -R log4cl calm/quicklisp/local-projects/log4cl
          export PATH=$PATH:$(pwd)/calm/
          export APP_NAME=Lem
          export APP_ICON="$(pwd)/assets/lem.png"
          calm publish
          ls -lah .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lem Linux
          if-no-files-found: error
          path: |
            *.AppImage

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.AppImage
  Lem-macOS:
    needs: macOS
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]

    env:
      CI_MATRIX_OS: ${{ matrix.os }}
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule update --init --recursive


      - name: Setup AppleScript for macOS 13
        if: ${{ matrix.os == 'macos-13' }}
        run: |
          sudo sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.finder',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e66696e64657200000003',NULL,1592919552);"
          sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.finder',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e66696e64657200000003',NULL,1592919552);"
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: CALM macOS

      - name: Build Lem
        run: |
          set -x
          rm -rf calm
          ls -lah
          export OS_SUBFIX=".${CI_MATRIX_OS}"
          cp calm${OS_SUBFIX}.dmg calm.dmg
          hdiutil attach calm.dmg
          cp -R "/Volumes/Calm - CALM/Calm.app/Contents/MacOS/" calm
          ls -lah calm
          cp -R lem calm/quicklisp/local-projects/lem
          cp -R log4cl calm/quicklisp/local-projects/log4cl
          rm *.dmg
          export PATH=$PATH:$(pwd)/calm/
          export APP_VERSION=2.0.0
          export APP_ID=com.vitovan.lem
          export APP_NAME=Lem
          export APP_ICON="$(pwd)/assets/lem.icns"
          export DMG_ICON="$(pwd)/assets/lem-dmg.icns"
          calm publish
          ls -lah .
          mv *.dmg Lem${OS_SUBFIX}.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lem macOS
          if-no-files-found: error
          path: |
            *.dmg

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.dmg

  Lem-Windows:
    needs: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule update --init --recursive


      - uses: msys2/setup-msys2@v2

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: CALM Windows

      - name: Build Lem
        shell: msys2 {0}
        run: |
          set -x
          rm -rf calm
          ls -lah
          pacman -S --noconfirm --needed unzip gcc libffi-devel
          unzip calm.zip
          ls -lah calm
          cp -R lem calm/quicklisp/local-projects/lem
          cp -R log4cl calm/quicklisp/local-projects/log4cl
          export PATH=$PATH:$(pwd)/calm/
          export APP_ICON="$(pwd)/assets/lem.ico"
          export APP_NAME=Lem
          calm publish
          mv ./*-Installer.exe ./Lem.exe
          ls -lah .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lem Windows
          if-no-files-found: error
          path: |
            *.exe

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.exe
